### ISSUE TITLE
Problem during the installation - bin/omnibus

### ISSUE THREAD

**Issue by LuKriZz** [rapid7/metasploit-omnibus#55]
Hi everybody,

I encountered a problem during the installation of metasploit with omnibus on Ubuntu 16.04.

Each steps have been successfully  completed:

- install required packages
- install omnibus' dependencies

But the build of metasploit-framework package failed.

Below the error:
```                   [CLI] I | 2017-06-28T11:50:17+02:00 | Using config from 'omnibus.rb'
[2017-06-28T11:50:18+02:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
 [Software: config_guess] W | 2017-06-28T11:50:19+02:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
Building metasploit-framework 4.15.0+20170628095018-1rapid7...
         [Software: zlib] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for zlib
      [Software: cacerts] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for cacerts
       [Software: xproto] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for xproto
  [Software: util-macros] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for util-macros
 [Software: config_guess] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for config_guess
 [Software: config_guess] W | 2017-06-28T11:50:19+02:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
 [Software: config_guess] W | 2017-06-28T11:50:19+02:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
[Software: pkg-config-lite] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for pkg-config-lite
   [Software: makedepend] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for makedepend
      [Software: openssl] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for openssl
      [Software: ncurses] I | 2017-06-28T11:50:19+02:00 | Resolving manifest entry for ncurses
    [NetFetcher: ncurses] I | 2017-06-28T11:50:19+02:00 | Downloading from `ftp://invisible-island.net/ncurses/current/ncurses-6.0-20150810.tgz'
      [Software: libedit] I | 2017-06-28T11:50:20+02:00 | Resolving manifest entry for libedit
    [NetFetcher: libedit] I | 2017-06-28T11:50:20+02:00 | Downloading from `http://www.thrysoee.dk/editline/libedit-20160903-3.1.tar.gz'
/usr/lib/ruby/2.3.0/net/ftp.rb:342:in `getresp': 550 ncurses-6.0-20150810.tgz: No such file or directory (Net::FTPPermError)
	from /usr/lib/ruby/2.3.0/net/ftp.rb:367:in `block in sendcmd'
	from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/lib/ruby/2.3.0/net/ftp.rb:365:in `sendcmd'
	from /usr/lib/ruby/2.3.0/net/ftp.rb:1040:in `block in size'
	from /usr/lib/ruby/2.3.0/net/ftp.rb:214:in `with_binary'
	from /usr/lib/ruby/2.3.0/net/ftp.rb:1039:in `size'
	from /usr/lib/ruby/2.3.0/open-uri.rb:790:in `buffer_open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/download_helpers.rb:80:in `download_file!'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/fetchers/net_fetcher.rb:173:in `download'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/software.rb:902:in `fetch'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/project.rb:1066:in `block (3 levels) in download'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/thread_pool.rb:62:in `loop'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/thread_pool.rb:61:in `catch'
	from /home/lucas/.bundler/ruby/2.3.0/omnibus-2d264d9e853e/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
```
I'm not a Ruby expert, and by far, so I've no idea about resolving this problem..

Thanks for your help.

**Comment by busterb** [comment]
Run 'git submodule update -i' before building. You may have to do a fresh checkout if you didn't do it before, this will pull in cached versions of all of the tarballs required to build omnibus.

Note, you don't really have to _build_ this project if you just want to install metasploit. We build this project every night for a number of platforms, info here: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

**Comment by busterb** [comment]
(we should probably update ncurses anyway, I'll take a look at doing that on the next package refresh)
