### ISSUE TITLE
The necessary IP address cannot be accessed.

### ISSUE THREAD

**Issue by notyeat** [rapid7/metasploit-omnibus#78]
I want to try msf5,so I tryed to compile it 
```#bin/omnibus build metasploit-framework```
the console displayed:
```
/usr/lib/ruby/2.5.0/socket.rb:64:in `connect': Connection timed out - connect(2) for 192.124.249.12:21 (Errno::ETIMEDOUT)
```
![image](https://user-images.githubusercontent.com/18442117/47193813-6a2a4180-d387-11e8-85be-8ae6815043ac.png)

so pity

it is verbose:
```
┌─[✗]─[root@parrot]─[/opt/metasploit-omnibus]
└──╼ #bin/omnibus build metasploit-framework
                    [CLI] I | 2018-10-18T01:29:45+08:00 | Using config from 'omnibus.rb'
 [Software: config_guess] W | 2018-10-18T01:29:54+08:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
Building metasploit-framework 4.17.10+20181017172945.git.3.dd382cf-1rapid7...
         [Software: zlib] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for zlib
      [Software: cacerts] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for cacerts
       [Software: xproto] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for xproto
  [Software: util-macros] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for util-macros
[Software: pkg-config-lite] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for pkg-config-lite
   [Software: makedepend] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for makedepend
      [Software: openssl] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for openssl
 [Software: config_guess] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for config_guess
 [Software: config_guess] W | 2018-10-18T01:29:55+08:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
 [Software: config_guess] W | 2018-10-18T01:29:55+08:00 | Version master for software config_guess was not parseable. Comparison methods such as #satisfies? will not be available for this version.
      [Software: ncurses] I | 2018-10-18T01:29:55+08:00 | Resolving manifest entry for ncurses
    [NetFetcher: ncurses] I | 2018-10-18T01:29:55+08:00 | Downloading from `ftp://invisible-island.net/ncurses/current/ncurses-6.0-20150810.tgz'
      [Software: libedit] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for libedit                                      0% (0 KB/sec)
      [Software: libtool] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for libtool
       [Software: libffi] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for libffi
      [Software: libyaml] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for libyaml
         [Software: ruby] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for ruby
     [Software: rubygems] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for rubygems
  [NullFetcher: rubygems] I | 2018-10-18T01:29:56+08:00 | Fetching `rubygems' (nothing to fetch)
      [Software: bundler] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for bundler
   [NullFetcher: bundler] I | 2018-10-18T01:29:56+08:00 | Fetching `bundler' (nothing to fetch)
      [Software: libpcap] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for libpcap
      [Software: pcaprub] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for pcaprub
   [NullFetcher: pcaprub] I | 2018-10-18T01:29:56+08:00 | Fetching `pcaprub' (nothing to fetch)
      [Software: liblzma] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for liblzma
      [Software: libxml2] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for libxml2
      [Software: libxslt] I | 2018-10-18T01:29:56+08:00 | Resolving manifest entry for libxslt
      [Software: libuuid] I | 2018-10-18T01:29:57+08:00 | Resolving manifest entry for libuuid
   [Software: postgresql] I | 2018-10-18T01:29:57+08:00 | Resolving manifest entry for postgresql
       [Software: sqlite] I | 2018-10-18T01:29:57+08:00 | Resolving manifest entry for sqlite
[Software: metasploit-framework] I | 2018-10-18T01:29:57+08:00 | Resolving manifest entry for metasploit-framework
[Software: metasploit-framework] W | 2018-10-18T01:29:57+08:00 | Version master for software metasploit-framework was not parseable. Comparison methods such as #satisfies? will not be available for this version.
[Software: metasploit-framework] W | 2018-10-18T01:29:57+08:00 | Version master for software metasploit-framework was not parseable. Comparison methods such as #satisfies? will not be available for this version.
[Software: metasploit-framework-wrappers] I | 2018-10-18T01:30:02+08:00 | Resolving manifest entry for metasploit-framework-wrappers
[NullFetcher: metasploit-framework-wrappers] I | 2018-10-18T01:30:02+08:00 | Fetching `metasploit-framework-wrappers' (nothing to fetch)
#<Thread:0x000056020e3f9bc8@/var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:57 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	30: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
	29: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:61:in `catch'
	28: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	27: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:62:in `loop'
	26: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	25: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/project.rb:1066:in `block (3 levels) in download'
	24: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/software.rb:897:in `fetch'
	23: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	22: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/fetchers/net_fetcher.rb:173:in `download'
	21: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/download_helpers.rb:80:in `download_file!'
	20: from /usr/lib/ruby/2.5.0/open-uri.rb:35:in `open'
	19: from /usr/lib/ruby/2.5.0/open-uri.rb:735:in `open'
	18: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	17: from /usr/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
	16: from /usr/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
	15: from /usr/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
	14: from /usr/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'
	13: from /usr/lib/ruby/2.5.0/open-uri.rb:793:in `buffer_open'
	12: from /usr/lib/ruby/2.5.0/net/ftp.rb:367:in `connect'
	11: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	10: from /usr/lib/ruby/2.5.0/net/ftp.rb:369:in `block in connect'
	 9: from /usr/lib/ruby/2.5.0/net/ftp.rb:328:in `open_socket'
	 8: from /usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
	 7: from /usr/lib/ruby/2.5.0/net/ftp.rb:333:in `block in open_socket'
	 6: from /usr/lib/ruby/2.5.0/socket.rb:631:in `tcp'
	 5: from /usr/lib/ruby/2.5.0/socket.rb:227:in `foreach'
	 4: from /usr/lib/ruby/2.5.0/socket.rb:227:in `each'
	 3: from /usr/lib/ruby/2.5.0/socket.rb:641:in `block in tcp'
	 2: from /usr/lib/ruby/2.5.0/socket.rb:137:in `connect'
	 1: from /usr/lib/ruby/2.5.0/socket.rb:64:in `connect_internal'
/usr/lib/ruby/2.5.0/socket.rb:64:in `connect': Connection timed out - connect(2) for 192.124.249.12:21 (Errno::ETIMEDOUT)
Traceback (most recent call last):
	30: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
	29: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:61:in `catch'
	28: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	27: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:62:in `loop'
	26: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	25: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/project.rb:1066:in `block (3 levels) in download'
	24: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/software.rb:897:in `fetch'
	23: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	22: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/fetchers/net_fetcher.rb:173:in `download'
	21: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/download_helpers.rb:80:in `download_file!'
	20: from /usr/lib/ruby/2.5.0/open-uri.rb:35:in `open'
	19: from /usr/lib/ruby/2.5.0/open-uri.rb:735:in `open'
	18: from /var/lib/gems/2.5.0/bundler/gems/omnibus-3a2d7755a617/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	17: from /usr/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
	16: from /usr/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
	15: from /usr/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
	14: from /usr/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'
	13: from /usr/lib/ruby/2.5.0/open-uri.rb:793:in `buffer_open'
	12: from /usr/lib/ruby/2.5.0/net/ftp.rb:367:in `connect'
	11: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	10: from /usr/lib/ruby/2.5.0/net/ftp.rb:369:in `block in connect'
	 9: from /usr/lib/ruby/2.5.0/net/ftp.rb:328:in `open_socket'
	 8: from /usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
	 7: from /usr/lib/ruby/2.5.0/net/ftp.rb:333:in `block in open_socket'
	 6: from /usr/lib/ruby/2.5.0/socket.rb:631:in `tcp'
	 5: from /usr/lib/ruby/2.5.0/socket.rb:227:in `foreach'
	 4: from /usr/lib/ruby/2.5.0/socket.rb:227:in `each'
	 3: from /usr/lib/ruby/2.5.0/socket.rb:641:in `block in tcp'
	 2: from /usr/lib/ruby/2.5.0/socket.rb:137:in `connect'
	 1: from /usr/lib/ruby/2.5.0/socket.rb:64:in `connect_internal'
/usr/lib/ruby/2.5.0/socket.rb:64:in `connect': Connection timed out - connect(2) for 192.124.249.12:21 (Errno::ETIMEDOUT)
```

**Comment by notyeat** [comment]
I trying your suggest:

```
Submodule 'local/cache'（https://github.com/rapid7/metasploit-omnibus-cache.git）No path 'local/cache' registration
fatal: Target path '/opt/metasploit-omnibus/local/cache' Already exists, and is not an empty directory
fatal: Unable to clone 'https://github.com/rapid7/metasploit-omnibus-cache.git' Submodule path '/opt/metasploit-omnibus/local/cache'
clone 'local/cache' default。按计划重试
fatal: Target path '/opt/metasploit-omnibus/local/cache'Already exists, and is not an empty directory。
fatal: Unable to clone 'https://github.com/rapid7/metasploit-omnibus-cache.git' Submodule path '/opt/metasploit-omnibus/local/cache'
The second attempt to clone 'local/cache' default
```

Should I  delete this path?

**Comment by busterb** [comment]
Yes, do that.

**Comment by pentestitde** [comment]
I did that:

fr@ubuntu:~/metasploit-omnibus$ rm -R /home/fr/metasploit-omnibus/local/cache
fr@ubuntu:~/metasploit-omnibus$ git submodule update -i
Cloning into '/home/fr/metasploit-omnibus/local/cache'...
Submodule path 'local/cache': checked out '7cad45e5886d0a9b3d397c86a65d66234986223a'

Now I get:

Traceback (most recent call last):
	20: from bin/omnibus:29:in `<main>'
	19: from bin/omnibus:29:in `load'
	18: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/bin/omnibus:16:in `<top (required)>'
	17: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/lib/omnibus/cli.rb:42:in `execute!'
	16: from /var/lib/gems/2.5.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	15: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/lib/omnibus/cli/base.rb:33:in `dispatch'
	14: from /var/lib/gems/2.5.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	13: from /var/lib/gems/2.5.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /var/lib/gems/2.5.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	11: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/lib/omnibus/cli.rb:89:in `build'
	10: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/lib/omnibus/project.rb:1075:in `build'
	 9: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/lib/omnibus/licensing.rb:57:in `create_incrementally'
	 8: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/lib/omnibus/licensing.rb:57:in `tap'
	 7: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/lib/omnibus/licensing.rb:59:in `block in create_incrementally'
	 6: from /home/frank/.bundle/ruby/2.5.0/omnibus-3a2d7755a617/lib/omnibus/licensing.rb:119:in `prepare'
	 5: from /usr/lib/ruby/2.5.0/fileutils.rb:1051:in `touch'
	 4: from /usr/lib/ruby/2.5.0/fileutils.rb:1051:in `each'
	 3: from /usr/lib/ruby/2.5.0/fileutils.rb:1053:in `block in touch'
	 2: from /usr/lib/ruby/2.5.0/fileutils.rb:1057:in `rescue in block in touch'
	 1: from /usr/lib/ruby/2.5.0/fileutils.rb:1057:in `open'
**/usr/lib/ruby/2.5.0/fileutils.rb:1057:in `initialize': Permission denied @ rb_sysopen - /opt/metasploit-framework/LICENSES/.gitkeep (Errno::EACCES)**

**Comment by pentestitde** [comment]
sudo chown -R user:user  /opt/metasploit-framework did it.

**Comment by notyeat** [comment]
Thank,I compiled MSF5 successfully,It's so cool!
